### ISSUE TITLE
Events and cleanHTML aren't available

### ISSUE THREAD

**Issue by floriansegginger** [steveathon/bootstrap-wysiwyg#122]
Using the very example given in this repo

````
  $('#question-editor').wysiwyg().on('change', function () {
    // Do something
  });
````

Just spits out a jQuery error:

````
jquery.min.js:2 Uncaught TypeError: Cannot read property 'on' of undefined
    at HTMLDocument.<anonymous> (poll.js:26)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
````

It seems the wysiwyg() function doesn't actually return anything anymore.

I would suggest updating the examples

**Comment by floriansegginger** [comment]
Unless I'm mistaken, this seems like a more serious problem where this plug-in is basically unusable in its current form. 

The Wysiwyg class is never exposed because it is in a self-calling function, and the jquery function doesn't return the newly created object. How can we do anything with this?

**Comment by spreadred** [comment]
@floriansegginger thanks, I've pushed this (minus the bower changes) to my fork!

**Comment by bartcoppens** [comment]
Issue is still there. I suggest to return the editor after the constructor to allow for chaining:
    $.fn.wysiwyg = function (userOptions) {
        var wysiwyg = new Wysiwyg(this, userOptions);
        **return wysiwyg.editor;**
    };
